set(CPP_HEADER_FILES
natl/container/all.h
natl/container/any.h
natl/container/array.h
natl/container/arrayView.h
natl/container/batchPool.h
natl/container/bitArray.h
natl/container/colony.h
natl/container/container.h
natl/container/dynArray.h
natl/container/flatHashMap.h
natl/container/flatHashSet.h
natl/container/functional.h
natl/container/functionCache.h
natl/container/heapArray.h
natl/container/partitioner.h
natl/container/persistentHashMap.h
natl/container/persistentHashSet.h
natl/container/priorityQueue.h
natl/container/smallDynArray.h
natl/container/string.h
natl/container/stringView.h
natl/container/variant.h
natl/container/view.h
natl/math/all.h
natl/math/basicFloatOperations.h
natl/math/constants.h
natl/math/exponential.h
natl/math/hyperbolic.h
natl/math/power.h
natl/math/satruatedArithmetic.h
natl/math/standard.h
natl/math/trigonometric.h
natl/processing/all.h
natl/processing/format.h
natl/processing/generator.h
natl/serialization/all.h
natl/serialization/base.h
natl/serialization/basicCompatibility.h
natl/serialization/basicSerializations.h
natl/serialization/compatibility.h
natl/serialization/error.h
natl/serialization/jump.h
natl/serialization/serializations.h
natl/serialization/utils.h
natl/simd/math/all.h
natl/simd/math/basicFloatOperations.h
natl/simd/all.h
natl/simd/cmaskOperations.h
natl/simd/math.h
natl/simd/operations.h
natl/simd/simdBase.h
natl/simd/simdClass.h
natl/simd/simdOf.h
natl/simd/standardArch.h
natl/sync/all.h
natl/sync/atomic.h
natl/sync/mutex.h
natl/sync/once.h
natl/sync/smartThread.h
natl/sync/synchronizedValue.h
natl/sync/thread.h
natl/system/all.h
natl/system/filesystem.h
natl/system/nullptrUtils.h
natl/system/print.h
natl/system/printColor.h
natl/system/printFormatted.h
natl/system/timer.h
natl/units/all.h
natl/units/base.h
natl/units/categoryConversion.h
natl/units/freedom.h
natl/units/imperial.h
natl/units/metric.h
natl/units/standard.h
natl/util/algorithm.h
natl/util/all.h
natl/util/allocator.h
natl/util/allocParts.h
natl/util/assert.h
natl/util/basicTypes.h
natl/util/bits.h
natl/util/bytes.h
natl/util/cast.h
natl/util/characterTest.h
natl/util/compare.h
natl/util/coroutines.h
natl/util/dataMovement.h
natl/util/enumUtils.h
natl/util/error.h
natl/util/executionSession.h
natl/util/expect.h
natl/util/funcArgs.h
natl/util/hash.h
natl/util/iteration.h
natl/util/iterators.h
natl/util/lexicographicalCompare.h
natl/util/limits.h
natl/util/main.h
natl/util/memory.h
natl/util/mixin.h
natl/util/numerics.h
natl/util/observerPtr.h
natl/util/option.h
natl/util/optionPtr.h
natl/util/owningPtr.h
natl/util/pair.h
natl/util/pointer.h
natl/util/random.h
natl/util/rawTypeInfo.h
natl/util/reflection.h
natl/util/smallestType.h
natl/util/sourceLocation.h
natl/util/stringConvert.h
natl/util/stringLiteral.h
natl/util/stringOperations.h
natl/util/strongType.h
natl/util/test.h
natl/util/tuple.h
natl/util/typeInfo.h
natl/util/typePack.h
natl/util/typeTraits.h
natl/util/uninitialized.h
natl/util/utility.h
natl/all.h)

set(CPP_SOURCE_FILES
natl/sync/mutex.cpp
natl/sync/thread.cpp
natl/system/filesystem.cpp
natl/system/nullptrUtils.cpp
natl/system/print.cpp
natl/system/printColor.cpp
natl/system/timer.cpp
natl/util/allocator.cpp
natl/util/executionSession.cpp
natl/util/memory.cpp
natl/util/test.cpp)

set(CPP_MODULE_INTERFACE_FILES
modules/natl/container/all.ixx
modules/natl/container/any.ixx
modules/natl/container/array.ixx
modules/natl/container/arrayView.ixx
modules/natl/container/batchPool.ixx
modules/natl/container/bitArray.ixx
modules/natl/container/colony.ixx
modules/natl/container/container.ixx
modules/natl/container/dynArray.ixx
modules/natl/container/flatHashMap.ixx
modules/natl/container/flatHashSet.ixx
modules/natl/container/functional.ixx
modules/natl/container/functionCache.ixx
modules/natl/container/heapArray.ixx
modules/natl/container/partitioner.ixx
modules/natl/container/persistentHashMap.ixx
modules/natl/container/persistentHashSet.ixx
modules/natl/container/priorityQueue.ixx
modules/natl/container/smallDynArray.ixx
modules/natl/container/string.ixx
modules/natl/container/stringView.ixx
modules/natl/container/variant.ixx
modules/natl/container/view.ixx
modules/natl/math/all.ixx
modules/natl/math/basicFloatOperations.ixx
modules/natl/math/constants.ixx
modules/natl/math/exponential.ixx
modules/natl/math/hyperbolic.ixx
modules/natl/math/power.ixx
modules/natl/math/satruatedArithmetic.ixx
modules/natl/math/standard.ixx
modules/natl/math/trigonometric.ixx
modules/natl/processing/all.ixx
modules/natl/processing/format.ixx
modules/natl/processing/generator.ixx
modules/natl/serialization/all.ixx
modules/natl/serialization/base.ixx
modules/natl/serialization/basicCompatibility.ixx
modules/natl/serialization/basicSerializations.ixx
modules/natl/serialization/compatibility.ixx
modules/natl/serialization/error.ixx
modules/natl/serialization/jump.ixx
modules/natl/serialization/serializations.ixx
modules/natl/serialization/utils.ixx
modules/natl/simd/math/all.ixx
modules/natl/simd/math/basicFloatOperations.ixx
modules/natl/simd/all.ixx
modules/natl/simd/cmaskOperations.ixx
modules/natl/simd/math.ixx
modules/natl/simd/operations.ixx
modules/natl/simd/simdBase.ixx
modules/natl/simd/simdClass.ixx
modules/natl/simd/simdOf.ixx
modules/natl/simd/standardArch.ixx
modules/natl/sync/all.ixx
modules/natl/sync/atomic.ixx
modules/natl/sync/mutex.ixx
modules/natl/sync/once.ixx
modules/natl/sync/smartThread.ixx
modules/natl/sync/synchronizedValue.ixx
modules/natl/sync/thread.ixx
modules/natl/system/all.ixx
modules/natl/system/filesystem.ixx
modules/natl/system/nullptrUtils.ixx
modules/natl/system/print.ixx
modules/natl/system/printColor.ixx
modules/natl/system/printFormatted.ixx
modules/natl/system/timer.ixx
modules/natl/units/all.ixx
modules/natl/units/base.ixx
modules/natl/units/categoryConversion.ixx
modules/natl/units/freedom.ixx
modules/natl/units/imperial.ixx
modules/natl/units/metric.ixx
modules/natl/units/standard.ixx
modules/natl/util/algorithm.ixx
modules/natl/util/all.ixx
modules/natl/util/allocator.ixx
modules/natl/util/allocParts.ixx
modules/natl/util/assert.ixx
modules/natl/util/basicTypes.ixx
modules/natl/util/bits.ixx
modules/natl/util/bytes.ixx
modules/natl/util/cast.ixx
modules/natl/util/characterTest.ixx
modules/natl/util/compare.ixx
modules/natl/util/coroutines.ixx
modules/natl/util/dataMovement.ixx
modules/natl/util/enumUtils.ixx
modules/natl/util/error.ixx
modules/natl/util/executionSession.ixx
modules/natl/util/expect.ixx
modules/natl/util/funcArgs.ixx
modules/natl/util/hash.ixx
modules/natl/util/iteration.ixx
modules/natl/util/iterators.ixx
modules/natl/util/lexicographicalCompare.ixx
modules/natl/util/limits.ixx
modules/natl/util/main.ixx
modules/natl/util/memory.ixx
modules/natl/util/mixin.ixx
modules/natl/util/numerics.ixx
modules/natl/util/observerPtr.ixx
modules/natl/util/option.ixx
modules/natl/util/optionPtr.ixx
modules/natl/util/owningPtr.ixx
modules/natl/util/pair.ixx
modules/natl/util/pointer.ixx
modules/natl/util/random.ixx
modules/natl/util/rawTypeInfo.ixx
modules/natl/util/reflection.ixx
modules/natl/util/smallestType.ixx
modules/natl/util/sourceLocation.ixx
modules/natl/util/stringConvert.ixx
modules/natl/util/stringLiteral.ixx
modules/natl/util/stringOperations.ixx
modules/natl/util/strongType.ixx
modules/natl/util/test.ixx
modules/natl/util/tuple.ixx
modules/natl/util/typeInfo.ixx
modules/natl/util/typePack.ixx
modules/natl/util/typeTraits.ixx
modules/natl/util/uninitialized.ixx
modules/natl/util/utility.ixx
modules/natl/all.ixx)

set(CPP_MODULE_IMPLEMENTATION_FILES
modules/natl/sync/mutex.cppm
modules/natl/sync/thread.cppm
modules/natl/system/filesystem.cppm
modules/natl/system/nullptrUtils.cppm
modules/natl/system/print.cppm
modules/natl/system/printColor.cppm
modules/natl/system/timer.cppm
modules/natl/util/allocator.cppm
modules/natl/util/executionSession.cppm
modules/natl/util/memory.cppm
modules/natl/util/test.cppm)

