#pragma once 

#include "compilerDependent.h"

#define NATL_IMPL_CONCAT_IMPL(x, y) x##y
#define NATL_CONCAT(x, y) NATL_IMPL_CONCAT_IMPL(x, y)
#define NATL_PLACE_HOLDER_NAME NATL_CONCAT(NatlPlaceHolder, NATL_COUNTER)

//repeat
//R = repeat
/*
    for i in range(101):
        print("#define NATL_IMPL_R"+ str(i) + "(X) NATL_IMPL_R"+ str(i - 1) + "(X) X")
*/
#define NATL_IMPL_R0(X) 
#define NATL_IMPL_R1(X) X
#define NATL_IMPL_R2(X) NATL_IMPL_R1(X) X
#define NATL_IMPL_R3(X) NATL_IMPL_R2(X) X
#define NATL_IMPL_R4(X) NATL_IMPL_R3(X) X
#define NATL_IMPL_R5(X) NATL_IMPL_R4(X) X
#define NATL_IMPL_R6(X) NATL_IMPL_R5(X) X
#define NATL_IMPL_R7(X) NATL_IMPL_R6(X) X
#define NATL_IMPL_R8(X) NATL_IMPL_R7(X) X
#define NATL_IMPL_R9(X) NATL_IMPL_R8(X) X
#define NATL_IMPL_R10(X) NATL_IMPL_R9(X) X
#define NATL_IMPL_R11(X) NATL_IMPL_R10(X) X
#define NATL_IMPL_R12(X) NATL_IMPL_R11(X) X
#define NATL_IMPL_R13(X) NATL_IMPL_R12(X) X
#define NATL_IMPL_R14(X) NATL_IMPL_R13(X) X
#define NATL_IMPL_R15(X) NATL_IMPL_R14(X) X
#define NATL_IMPL_R16(X) NATL_IMPL_R15(X) X
#define NATL_IMPL_R17(X) NATL_IMPL_R16(X) X
#define NATL_IMPL_R18(X) NATL_IMPL_R17(X) X
#define NATL_IMPL_R19(X) NATL_IMPL_R18(X) X
#define NATL_IMPL_R20(X) NATL_IMPL_R19(X) X
#define NATL_IMPL_R21(X) NATL_IMPL_R20(X) X
#define NATL_IMPL_R22(X) NATL_IMPL_R21(X) X
#define NATL_IMPL_R23(X) NATL_IMPL_R22(X) X
#define NATL_IMPL_R24(X) NATL_IMPL_R23(X) X
#define NATL_IMPL_R25(X) NATL_IMPL_R24(X) X
#define NATL_IMPL_R26(X) NATL_IMPL_R25(X) X
#define NATL_IMPL_R27(X) NATL_IMPL_R26(X) X
#define NATL_IMPL_R28(X) NATL_IMPL_R27(X) X
#define NATL_IMPL_R29(X) NATL_IMPL_R28(X) X
#define NATL_IMPL_R30(X) NATL_IMPL_R29(X) X
#define NATL_IMPL_R31(X) NATL_IMPL_R30(X) X
#define NATL_IMPL_R32(X) NATL_IMPL_R31(X) X
#define NATL_IMPL_R33(X) NATL_IMPL_R32(X) X
#define NATL_IMPL_R34(X) NATL_IMPL_R33(X) X
#define NATL_IMPL_R35(X) NATL_IMPL_R34(X) X
#define NATL_IMPL_R36(X) NATL_IMPL_R35(X) X
#define NATL_IMPL_R37(X) NATL_IMPL_R36(X) X
#define NATL_IMPL_R38(X) NATL_IMPL_R37(X) X
#define NATL_IMPL_R39(X) NATL_IMPL_R38(X) X
#define NATL_IMPL_R40(X) NATL_IMPL_R39(X) X
#define NATL_IMPL_R41(X) NATL_IMPL_R40(X) X
#define NATL_IMPL_R42(X) NATL_IMPL_R41(X) X
#define NATL_IMPL_R43(X) NATL_IMPL_R42(X) X
#define NATL_IMPL_R44(X) NATL_IMPL_R43(X) X
#define NATL_IMPL_R45(X) NATL_IMPL_R44(X) X
#define NATL_IMPL_R46(X) NATL_IMPL_R45(X) X
#define NATL_IMPL_R47(X) NATL_IMPL_R46(X) X
#define NATL_IMPL_R48(X) NATL_IMPL_R47(X) X
#define NATL_IMPL_R49(X) NATL_IMPL_R48(X) X
#define NATL_IMPL_R50(X) NATL_IMPL_R49(X) X
#define NATL_IMPL_R51(X) NATL_IMPL_R50(X) X
#define NATL_IMPL_R52(X) NATL_IMPL_R51(X) X
#define NATL_IMPL_R53(X) NATL_IMPL_R52(X) X
#define NATL_IMPL_R54(X) NATL_IMPL_R53(X) X
#define NATL_IMPL_R55(X) NATL_IMPL_R54(X) X
#define NATL_IMPL_R56(X) NATL_IMPL_R55(X) X
#define NATL_IMPL_R57(X) NATL_IMPL_R56(X) X
#define NATL_IMPL_R58(X) NATL_IMPL_R57(X) X
#define NATL_IMPL_R59(X) NATL_IMPL_R58(X) X
#define NATL_IMPL_R60(X) NATL_IMPL_R59(X) X
#define NATL_IMPL_R61(X) NATL_IMPL_R60(X) X
#define NATL_IMPL_R62(X) NATL_IMPL_R61(X) X
#define NATL_IMPL_R63(X) NATL_IMPL_R62(X) X
#define NATL_IMPL_R64(X) NATL_IMPL_R63(X) X
#define NATL_IMPL_R65(X) NATL_IMPL_R64(X) X
#define NATL_IMPL_R66(X) NATL_IMPL_R65(X) X
#define NATL_IMPL_R67(X) NATL_IMPL_R66(X) X
#define NATL_IMPL_R68(X) NATL_IMPL_R67(X) X
#define NATL_IMPL_R69(X) NATL_IMPL_R68(X) X
#define NATL_IMPL_R70(X) NATL_IMPL_R69(X) X
#define NATL_IMPL_R71(X) NATL_IMPL_R70(X) X
#define NATL_IMPL_R72(X) NATL_IMPL_R71(X) X
#define NATL_IMPL_R73(X) NATL_IMPL_R72(X) X
#define NATL_IMPL_R74(X) NATL_IMPL_R73(X) X
#define NATL_IMPL_R75(X) NATL_IMPL_R74(X) X
#define NATL_IMPL_R76(X) NATL_IMPL_R75(X) X
#define NATL_IMPL_R77(X) NATL_IMPL_R76(X) X
#define NATL_IMPL_R78(X) NATL_IMPL_R77(X) X
#define NATL_IMPL_R79(X) NATL_IMPL_R78(X) X
#define NATL_IMPL_R80(X) NATL_IMPL_R79(X) X
#define NATL_IMPL_R81(X) NATL_IMPL_R80(X) X
#define NATL_IMPL_R82(X) NATL_IMPL_R81(X) X
#define NATL_IMPL_R83(X) NATL_IMPL_R82(X) X
#define NATL_IMPL_R84(X) NATL_IMPL_R83(X) X
#define NATL_IMPL_R85(X) NATL_IMPL_R84(X) X
#define NATL_IMPL_R86(X) NATL_IMPL_R85(X) X
#define NATL_IMPL_R87(X) NATL_IMPL_R86(X) X
#define NATL_IMPL_R88(X) NATL_IMPL_R87(X) X
#define NATL_IMPL_R89(X) NATL_IMPL_R88(X) X
#define NATL_IMPL_R90(X) NATL_IMPL_R89(X) X
#define NATL_IMPL_R91(X) NATL_IMPL_R90(X) X
#define NATL_IMPL_R92(X) NATL_IMPL_R91(X) X
#define NATL_IMPL_R93(X) NATL_IMPL_R92(X) X
#define NATL_IMPL_R94(X) NATL_IMPL_R93(X) X
#define NATL_IMPL_R95(X) NATL_IMPL_R94(X) X
#define NATL_IMPL_R96(X) NATL_IMPL_R95(X) X
#define NATL_IMPL_R97(X) NATL_IMPL_R96(X) X
#define NATL_IMPL_R98(X) NATL_IMPL_R97(X) X
#define NATL_IMPL_R99(X) NATL_IMPL_R98(X) X
#define NATL_IMPL_R100(X) NATL_IMPL_R99(X) X

#define NATL_REPEAT(D1,X) NATL_IMPL_R##D1(X)

//repeat with comma
//RC = repeat commas 
/*
    for i in range(101):
        print("#define NATL_IMPL_RC"+ str(i) + "(X) NATL_IMPL_RC"+ str(i - 1) + "(X) , X")
*/
#define NATL_IMPL_RC0(X)
#define NATL_IMPL_RC1(X) X
#define NATL_IMPL_RC2(X) NATL_IMPL_RC1(X), X
#define NATL_IMPL_RC3(X) NATL_IMPL_RC2(X), X
#define NATL_IMPL_RC4(X) NATL_IMPL_RC3(X), X
#define NATL_IMPL_RC5(X) NATL_IMPL_RC4(X), X
#define NATL_IMPL_RC6(X) NATL_IMPL_RC5(X), X
#define NATL_IMPL_RC7(X) NATL_IMPL_RC6(X), X
#define NATL_IMPL_RC8(X) NATL_IMPL_RC7(X), X
#define NATL_IMPL_RC9(X) NATL_IMPL_RC8(X), X
#define NATL_IMPL_RC10(X) NATL_IMPL_RC9(X), X
#define NATL_IMPL_RC11(X) NATL_IMPL_RC10(X), X
#define NATL_IMPL_RC12(X) NATL_IMPL_RC11(X), X
#define NATL_IMPL_RC13(X) NATL_IMPL_RC12(X), X
#define NATL_IMPL_RC14(X) NATL_IMPL_RC13(X), X
#define NATL_IMPL_RC15(X) NATL_IMPL_RC14(X), X
#define NATL_IMPL_RC16(X) NATL_IMPL_RC15(X), X
#define NATL_IMPL_RC17(X) NATL_IMPL_RC16(X), X
#define NATL_IMPL_RC18(X) NATL_IMPL_RC17(X), X
#define NATL_IMPL_RC19(X) NATL_IMPL_RC18(X), X
#define NATL_IMPL_RC20(X) NATL_IMPL_RC19(X), X
#define NATL_IMPL_RC21(X) NATL_IMPL_RC20(X), X
#define NATL_IMPL_RC22(X) NATL_IMPL_RC21(X), X
#define NATL_IMPL_RC23(X) NATL_IMPL_RC22(X), X
#define NATL_IMPL_RC24(X) NATL_IMPL_RC23(X), X
#define NATL_IMPL_RC25(X) NATL_IMPL_RC24(X), X
#define NATL_IMPL_RC26(X) NATL_IMPL_RC25(X), X
#define NATL_IMPL_RC27(X) NATL_IMPL_RC26(X), X
#define NATL_IMPL_RC28(X) NATL_IMPL_RC27(X), X
#define NATL_IMPL_RC29(X) NATL_IMPL_RC28(X), X
#define NATL_IMPL_RC30(X) NATL_IMPL_RC29(X), X
#define NATL_IMPL_RC31(X) NATL_IMPL_RC30(X), X
#define NATL_IMPL_RC32(X) NATL_IMPL_RC31(X), X
#define NATL_IMPL_RC33(X) NATL_IMPL_RC32(X), X
#define NATL_IMPL_RC34(X) NATL_IMPL_RC33(X), X
#define NATL_IMPL_RC35(X) NATL_IMPL_RC34(X), X
#define NATL_IMPL_RC36(X) NATL_IMPL_RC35(X), X
#define NATL_IMPL_RC37(X) NATL_IMPL_RC36(X), X
#define NATL_IMPL_RC38(X) NATL_IMPL_RC37(X), X
#define NATL_IMPL_RC39(X) NATL_IMPL_RC38(X), X
#define NATL_IMPL_RC40(X) NATL_IMPL_RC39(X), X
#define NATL_IMPL_RC41(X) NATL_IMPL_RC40(X), X
#define NATL_IMPL_RC42(X) NATL_IMPL_RC41(X), X
#define NATL_IMPL_RC43(X) NATL_IMPL_RC42(X), X
#define NATL_IMPL_RC44(X) NATL_IMPL_RC43(X), X
#define NATL_IMPL_RC45(X) NATL_IMPL_RC44(X), X
#define NATL_IMPL_RC46(X) NATL_IMPL_RC45(X), X
#define NATL_IMPL_RC47(X) NATL_IMPL_RC46(X), X
#define NATL_IMPL_RC48(X) NATL_IMPL_RC47(X), X
#define NATL_IMPL_RC49(X) NATL_IMPL_RC48(X), X
#define NATL_IMPL_RC50(X) NATL_IMPL_RC49(X), X
#define NATL_IMPL_RC51(X) NATL_IMPL_RC50(X), X
#define NATL_IMPL_RC52(X) NATL_IMPL_RC51(X), X
#define NATL_IMPL_RC53(X) NATL_IMPL_RC52(X), X
#define NATL_IMPL_RC54(X) NATL_IMPL_RC53(X), X
#define NATL_IMPL_RC55(X) NATL_IMPL_RC54(X), X
#define NATL_IMPL_RC56(X) NATL_IMPL_RC55(X), X
#define NATL_IMPL_RC57(X) NATL_IMPL_RC56(X), X
#define NATL_IMPL_RC58(X) NATL_IMPL_RC57(X), X
#define NATL_IMPL_RC59(X) NATL_IMPL_RC58(X), X
#define NATL_IMPL_RC60(X) NATL_IMPL_RC59(X), X
#define NATL_IMPL_RC61(X) NATL_IMPL_RC60(X), X
#define NATL_IMPL_RC62(X) NATL_IMPL_RC61(X), X
#define NATL_IMPL_RC63(X) NATL_IMPL_RC62(X), X
#define NATL_IMPL_RC64(X) NATL_IMPL_RC63(X), X
#define NATL_IMPL_RC65(X) NATL_IMPL_RC64(X), X
#define NATL_IMPL_RC66(X) NATL_IMPL_RC65(X), X
#define NATL_IMPL_RC67(X) NATL_IMPL_RC66(X), X
#define NATL_IMPL_RC68(X) NATL_IMPL_RC67(X), X
#define NATL_IMPL_RC69(X) NATL_IMPL_RC68(X), X
#define NATL_IMPL_RC70(X) NATL_IMPL_RC69(X), X
#define NATL_IMPL_RC71(X) NATL_IMPL_RC70(X), X
#define NATL_IMPL_RC72(X) NATL_IMPL_RC71(X), X
#define NATL_IMPL_RC73(X) NATL_IMPL_RC72(X), X
#define NATL_IMPL_RC74(X) NATL_IMPL_RC73(X), X
#define NATL_IMPL_RC75(X) NATL_IMPL_RC74(X), X
#define NATL_IMPL_RC76(X) NATL_IMPL_RC75(X), X
#define NATL_IMPL_RC77(X) NATL_IMPL_RC76(X), X
#define NATL_IMPL_RC78(X) NATL_IMPL_RC77(X), X
#define NATL_IMPL_RC79(X) NATL_IMPL_RC78(X), X
#define NATL_IMPL_RC80(X) NATL_IMPL_RC79(X), X
#define NATL_IMPL_RC81(X) NATL_IMPL_RC80(X), X
#define NATL_IMPL_RC82(X) NATL_IMPL_RC81(X), X
#define NATL_IMPL_RC83(X) NATL_IMPL_RC82(X), X
#define NATL_IMPL_RC84(X) NATL_IMPL_RC83(X), X
#define NATL_IMPL_RC85(X) NATL_IMPL_RC84(X), X
#define NATL_IMPL_RC86(X) NATL_IMPL_RC85(X), X
#define NATL_IMPL_RC87(X) NATL_IMPL_RC86(X), X
#define NATL_IMPL_RC88(X) NATL_IMPL_RC87(X), X
#define NATL_IMPL_RC89(X) NATL_IMPL_RC88(X), X
#define NATL_IMPL_RC90(X) NATL_IMPL_RC89(X), X
#define NATL_IMPL_RC91(X) NATL_IMPL_RC90(X), X
#define NATL_IMPL_RC92(X) NATL_IMPL_RC91(X), X
#define NATL_IMPL_RC93(X) NATL_IMPL_RC92(X), X
#define NATL_IMPL_RC94(X) NATL_IMPL_RC93(X), X
#define NATL_IMPL_RC95(X) NATL_IMPL_RC94(X), X
#define NATL_IMPL_RC96(X) NATL_IMPL_RC95(X), X
#define NATL_IMPL_RC97(X) NATL_IMPL_RC96(X), X
#define NATL_IMPL_RC98(X) NATL_IMPL_RC97(X), X
#define NATL_IMPL_RC99(X) NATL_IMPL_RC98(X), X
#define NATL_IMPL_RC100(X) NATL_IMPL_RC99(X), X

#define NATL_REPEAT_WITH_COMMAS(D1,X) NATL_IMPL_RC##D1(X)
